services:
  - type: web
    name: lem-birthday-app
    runtime: docker
    repo: https://github.com/19-5-12/Lem
    branch: master
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - fromGroup: lem-app-env
